.TH "hal.maths.crypt.MD6" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.crypt.MD6 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, string, size)"
.br
.ti -1c
.RI "def \fBhash\fP (self)"
.br
.ti -1c
.RI "def \fBhex\fP (self, data, size)"
.br
.ti -1c
.RI "def \fBraw\fP (self, data, size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplain\fP"
.br
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBhashed\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBALLOWED_SIZE\fP = [64, 128, 224, 256, 384, 512]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
md6 hash 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.crypt\&.MD6\&.hash ( self)"

.PP
.nf
:return: return md6 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.MD6\&.hex ( self,  data,  size)"

.PP
.nf
:param data: plaintext
:param size: bytes
:return: hex representation

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.MD6\&.raw ( self,  data,  size)"

.PP
.nf
:param data: plaintext
:param size: bytes
:return: raw representation

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
