.TH "hal.maths.plotter.Plot3d" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.plotter.Plot3d \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBparam\fP (self, functionx, functiony, functionz, min, max, points)"
.br
.ti -1c
.RI "def \fBplot\fP (self, function, minx, maxx, pointsx, miny, maxy, pointsy)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBscatter\fP (vectorx, vectory, vectorz)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.plotter\&.Plot3d\&.param ( self,  functionx,  functiony,  functionz,  min,  max,  points)"

.PP
.nf
:param functionx: function in x
:param functiony: function in y
:param functionz: function in z
:param min: minimum
:param max: maximum
:param points: number of points
:return: 3d parametric graph of given function from min to max

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot3d\&.plot ( self,  function,  minx,  maxx,  pointsx,  miny,  maxy,  pointsy)"

.PP
.nf
:param function: function to plot
:param minx: minimum of x-values
:param maxx: maximum of x-values
:param pointsx: points in x axis
:param miny: minimum of y-values
:param maxy: maximum of y-values
:param pointsy: points in y axis
:return: plot 3d function

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot3d\&.scatter ( vectorx,  vectory,  vectorz)\fC [static]\fP"

.PP
.nf
:param vectorx: vector in x axis
:param vectory: vector in y axis
:param vectorz: vector in z axis
:return: plot 3d scattered points

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
