.TH "hal.internet.parser.HtmlTable" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.internet.parser.HtmlTable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits str\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, html_source)"
.br
.ti -1c
.RI "def \fBparse\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsource\fP"
.br
.ti -1c
.RI "\fBsoup\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def hal\&.internet\&.parser\&.HtmlTable\&.__init__ ( self,  html_source)"

.PP
.nf
:param html_source: string
    Html source of table

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.internet\&.parser\&.HtmlTable\&.parse ( self)"

.PP
.nf
:return: list of list
    List of list of values in table

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
