.TH "hal.files.models.MP3Song" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.files.models.MP3Song \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhal\&.files\&.models\&.FileSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, path)"
.br
.ti -1c
.RI "def \fBset_name\fP (self, name)"
.br
.ti -1c
.RI "def \fBset_artist\fP (self, artist)"
.br
.ti -1c
.RI "def \fBset_album\fP (self, album)"
.br
.ti -1c
.RI "def \fBset_nr_track\fP (self, nr_track)"
.br
.ti -1c
.RI "def \fBset_year\fP (self, year)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsong\fP"
.br
.ti -1c
.RI "\fBtags\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
mp3 song 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
