.TH "hal.maths.plotter.Plot4d" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.plotter.Plot4d \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBparam\fP (self, functionx, functiony, functionz, functionw, min, max, points)"
.br
.ti -1c
.RI "def \fBplot\fP (self, function, minx, maxx, miny, maxy, minz, maxz, precision, kind)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBscatter\fP (vectorx, vectory, vectorz, vectorw)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.plotter\&.Plot4d\&.param ( self,  functionx,  functiony,  functionz,  functionw,  min,  max,  points)"

.PP
.nf
:param functionx: function in x
:param functiony: function in y
:param functionz: function in z
:param functionw: function in w
:param min: minimum
:param max: maximum
:param points: number of points
:return: 4d parametric graph of given function from min to max

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot4d\&.plot ( self,  function,  minx,  maxx,  miny,  maxy,  minz,  maxz,  precision,  kind)"

.PP
.nf
:param function: function to plot
:param minx: minimum of x-values
:param maxx: maximum of x-values
:param miny: minimum of y-values
:param maxy: maximum of y-values
:param minz: minimum of z-values
:param maxz: maximum of z-values
:param precision: precision
:param kind: slice: x cont -> 3d plot with y,z variables in plane and w as "z"-axis
     contour: x cont -> 3d plot with y,z variables in plane and w colored
:return: plot 4d function

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot4d\&.scatter ( vectorx,  vectory,  vectorz,  vectorw)\fC [static]\fP"

.PP
.nf
:param vectorx: vector in x axis
:param vectory: vector in y axis
:param vectorz: vector in z axis
:param vectorw: vector in w axis
:return: plot 4d scattered points

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
