.TH "hal.profile.performance.EightQueenTest" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.profile.performance.EightQueenTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, size)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBwelcome\fP ()"
.br
.ti -1c
.RI "def \fBintroduction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
test CPU by solving eight-queen problem 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.profile\&.performance\&.EightQueenTest\&.introduction ()\fC [static]\fP"

.PP
.nf
:return: introduce 8 queen problem 
.fi
.PP
 
.SS "def hal\&.profile\&.performance\&.EightQueenTest\&.welcome ()\fC [static]\fP"

.PP
.nf
:return: introduce script 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
