.TH "hal.internet.web.Webpage" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.internet.web.Webpage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, url, using_tor=False)"
.br
.ti -1c
.RI "def \fBget_scheme\fP (self)"
.br
.ti -1c
.RI "def \fBget_hostname\fP (self)"
.br
.ti -1c
.RI "def \fBget_domain\fP (self)"
.br
.ti -1c
.RI "def \fBget_html_source\fP (self, tor=False)"
.br
.ti -1c
.RI "def \fBget_links\fP (self, recall, timeout)"
.br
.ti -1c
.RI "def \fBopen_in_browser\fP (self, times)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBparse_url\fP (raw_url)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBdomain\fP"
.br
.ti -1c
.RI "\fBusing_tor\fP"
.br
.ti -1c
.RI "\fBsource\fP"
.br
.ti -1c
.RI "\fBsoup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
representation of URL (web page)
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def hal\&.internet\&.web\&.Webpage\&.__init__ ( self,  url,  using_tor = \fCFalse\fP)"

.PP
.nf
:param url: string
    Url of webpage
:param using_tor: bool
    Whether using tor or not to fetch source page

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.internet\&.web\&.Webpage\&.get_domain ( self)"

.PP
.nf
:return: get domain from given url

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.get_hostname ( self)"

.PP
.nf
:return: extract hostname from given url

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.get_html_source ( self,  tor = \fCFalse\fP)"

.PP
.nf
:return: BeautifulSoup to parse

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.get_links ( self,  recall,  timeout)"

.PP
.nf
:param recall: max time to attempt to fetch url
:param timeout: max time (s) to wait for web_page response
:return: array of out_links

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.get_scheme ( self)"

.PP
.nf
:return: get scheme (HTTP, HTTPS, FTP ..) from given url

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.open_in_browser ( self,  times)"

.PP
.nf
:param times: int
    Times to open webpage in browser
:return: void
    Open a wendrive and go to webpage

.fi
.PP
 
.SS "def hal\&.internet\&.web\&.Webpage\&.parse_url ( raw_url)\fC [static]\fP"

.PP
.nf
:param raw_url: url to parse
:return: parses correctly url

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
