.TH "hal.ml.data.parser.CSVParser" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.ml.data.parser.CSVParser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhal\&.ml\&.data\&.parser\&.Parser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, database_file)"
.br
.ti -1c
.RI "def \fBparse_data\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def hal\&.ml\&.data\&.parser\&.CSVParser\&.__init__ ( self,  database_file)"

.PP
.nf
:param database_file: a raw .csv file that contains any data about anything 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.ml\&.data\&.parser\&.CSVParser\&.parse_data ( self)"

.PP
.nf
store values in array, store lines in array; the result is a 2D matrix
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
