.TH "hal.internet.engines.SearchEngineResult" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.internet.engines.SearchEngineResult \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, title, link, description='')"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBlink\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
