.TH "hal.maths.crypt.SHA" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.crypt.SHA \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, string, size, salt=None)"
.br
.ti -1c
.RI "def \fBhash\fP (self)"
.br
.ti -1c
.RI "def \fBhash_sha1\fP (self)"
.br
.ti -1c
.RI "def \fBhash_sha224\fP (self)"
.br
.ti -1c
.RI "def \fBhash_sha256\fP (self)"
.br
.ti -1c
.RI "def \fBhash_sha384\fP (self)"
.br
.ti -1c
.RI "def \fBhash_sha512\fP (self)"
.br
.ti -1c
.RI "def \fBhash_shasalted\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplain\fP"
.br
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBsalt\fP"
.br
.ti -1c
.RI "\fBhashed\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBALLOWED_SIZE\fP = [1, 224, 256, 384, 512]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
general SHA hash 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash ( self)"

.PP
.nf
:return: hash of given size

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_sha1 ( self)"

.PP
.nf
:return: sha1 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_sha224 ( self)"

.PP
.nf
:return: sha224 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_sha256 ( self)"

.PP
.nf
:return: sha256 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_sha384 ( self)"

.PP
.nf
:return: sha384 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_sha512 ( self)"

.PP
.nf
:return: sha512 hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.SHA\&.hash_shasalted ( self)"

.PP
.nf
:return: sha512 hash

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
