.TH "hal.maths.crypt.IDEA" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.crypt.IDEA \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, string, key)"
.br
.ti -1c
.RI "def \fBhash\fP (self)"
.br
.ti -1c
.RI "def \fBchange_key\fP (self, key)"
.br
.ti -1c
.RI "def \fBencrypt\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplain\fP"
.br
.ti -1c
.RI "\fBhashed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
IDEA hash 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.crypt\&.IDEA\&.change_key ( self,  key)"

.PP
.nf
:param key: new key
:return: change key

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.IDEA\&.encrypt ( self)"

.PP
.nf
:return: encrypt with key

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.IDEA\&.hash ( self)"

.PP
.nf
:return: IDEA hash

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
