.TH "hal.ml.predict.BasePrediction" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.ml.predict.BasePrediction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, model, rounds)"
.br
.ti -1c
.RI "def \fBtrain\fP (self, x, y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP"
.br
.ti -1c
.RI "\fBrounds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
