.TH "hal.ml.data.parser.Parser" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.ml.data.parser.Parser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBhal\&.ml\&.data\&.parser\&.CSVParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, database_file)"
.br
.ti -1c
.RI "def \fBget_lines\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdatabase_file\fP"
.br
.ti -1c
.RI "\fBlines\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def hal\&.ml\&.data\&.parser\&.Parser\&.__init__ ( self,  database_file)"

.PP
.nf
:param database_file: a raw .csv file that contains any data about anything 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
