.TH "hal.maths.plotter.Plot2d" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.plotter.Plot2d \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBparam\fP (self, functionx, functiony, min, max, points)"
.br
.ti -1c
.RI "def \fBplot\fP (self, function, min, max, points)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBscatter\fP (vectorx, vectory)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
2d plot 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.plotter\&.Plot2d\&.param ( self,  functionx,  functiony,  min,  max,  points)"

.PP
.nf
:param functionx: function in x value
:param functiony: function in y value
::param min: minimum value
:param max: maximum value
:param points: number of points to display
:return: 2d parametric graph of given function from min to max

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot2d\&.plot ( self,  function,  min,  max,  points)"

.PP
.nf
:param function: function to plot
:param min: minimum value
:param max: maximum value
:param points: number of points
:return: plot 2d function

.fi
.PP
 
.SS "def hal\&.maths\&.plotter\&.Plot2d\&.scatter ( vectorx,  vectory)\fC [static]\fP"

.PP
.nf
:param vectorx: vector in x axis
:param vectory: vector in y axis
:return: 2d scatter plot

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
