.TH "hal.maths.crypt.BLOWFISH" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.crypt.BLOWFISH \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, string, key)"
.br
.ti -1c
.RI "def \fBhash\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplain\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBhashed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
blowfish hash 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.crypt\&.BLOWFISH\&.hash ( self)"

.PP
.nf
:return: hash plaintext

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
