.TH "hal.maths.crypt.ARC" 3 "Tue Jan 10 2017" "Version 4.3" "PyHal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hal.maths.crypt.ARC \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, string, key, size)"
.br
.ti -1c
.RI "def \fBhash\fP (self)"
.br
.ti -1c
.RI "def \fBhash_ar2\fP (self)"
.br
.ti -1c
.RI "def \fBhash_arc4\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBplain\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBsize\fP"
.br
.ti -1c
.RI "\fBhashed\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBALLOWED_SIZE\fP = [2, 4]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
ARC hash 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def hal\&.maths\&.crypt\&.ARC\&.hash ( self)"

.PP
.nf
:return: hash of given size

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.ARC\&.hash_ar2 ( self)"

.PP
.nf
:return: des hash

.fi
.PP
 
.SS "def hal\&.maths\&.crypt\&.ARC\&.hash_arc4 ( self)"

.PP
.nf
:return: des3 hash

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PyHal from the source code\&.
